### ISSUE TITLE
Optimize selection of candidate annotations to be voted

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#133]
For speeding up the creation of a high quality dataset, we use some **prioritization** when selecting the candidate annotations that are presented to a user executing a _validate annotation task_ #69.

**Currently**, we select the annotations in several steps. After each steps, if the number of selected annotations is less than 12 (number of annotations to vote in one form), we go for the next step:
(I am not including verification annotations that are first selected).

1. The ones that have been already voted at least once
   1. correspond to short clips (< 10 sec)
   2. correspond to long clips (> 10 sec)
2. The ones that have no vote
   1. correspond to short clips (< 10 sec)
   2. correspond to long clips (> 10 sec)

Inside each steps, we also prioritize annotations that correspond to sound that have some other ground truth annotations (for _complete labeling_, see `get_candidate_annotations_complete_ids_random_from` _datasets_ view function).

---

**This steps are hard to understand, test and debug** (see `contribute_validate_annotations_category` _datasets_ view function). 
One way to do the selection more efficiently, is to have numerical value(s) associated to the annotations, which allows to sort them by priority. To allow efficient database sorting, we need to have this(ese) value(s) stored (and indexed).
<br />
**First**, we could have one value that reflect the different aspect to take into account for prioritization:
```
candidate_annotation.priority_score =  
             1000 * num_votes
           +  100 * length_related_score (3: <10sec, 2: <20sec, ... ) 
           +    1 * num_gt_same_sound
```

I think this score can be real time, by updating the score of an annotation every time a:
- _vote_ is created
- _ground truth annotation_ associated to the same sound is created (except the propagated ones)
<br />

**Then**, to select the candidate annotations, an SQL query can do the sorting (similar to the one in `get_candidate_annotations_complete_ids_random_from` _datasets_ view function):
- order by _priority score_
- randomize

The SQL query seems to be the best choice, since with the Django ORM, applying two orderings (priority score and random) fails.

**Comment by xavierfav** [comment]
This feature has been implemented together with some tests on the prioritization of short and medium duration sounds.

The cool thing now is that it is easy to do some tweak on the priority score in order to prioritize or discard some candidate annotations.
@jordipons proposed some nice idea in order to collect quicker Present samples.
Can you develop here?

Here is how the priority score is implemented now:
```
def return_priority_score(self):
    sound = self.sound_dataset.sound
    sound_duration = sound.extra_data['duration']

    if not 0.3 <= sound_duration <= 30:
        return self.votes.count()

    else:
        duration_score = 3 if sound_duration <= 10 else 2 if sound_duration <= 20 else 1
        num_gt_same_sound = self.sound_dataset.ground_truth_annotations.filter(from_propagation=False).count()

        return 1000 * self.votes.count()\
             +  100 * duration_score\
             +        num_gt_same_sound
```
For a given candidate annotation, num_gt_same_sound correspond to the number of (present) ground truth annotations the associated sound has (to get faster to a complete labeling of sound samples).

Candidate annotations with a priority score of 0 are discarded and therefore crowd-worker cannot annotate them.

**Comment by jordipons** [comment]
The interesting aspect of this flexible score is that we can change it "on the fly" according to our needs.

Given that our goals are now centered in getting positive ground truth annotations, we propose to change this score according to that.

Basically, we propose to change the last return to (pseudo-code):
`1000 * self.votes.count(PP,PNP) + 100 * duration_score + num_gt_same_sound`

In short, we propose to prioritize: first, sounds with positive votes; then, short sounds; and finally, sounds which have a ground truth in another category (to fully annotate these sounds to cover all their occurring audio events).

This modification has the collateral effect that negative long audios will not be prioritized, and short audios without any votes (with some chances to be positive) will have the possibility to show up. In other words: NP, U, and non-voted sounds will be prioritized only depending on its length (shorter sounds, first).

Although this might have some effect in categories having many candidates, we do not expect to have any effect for categories having just a few candidates (since we will be voting all of them regardless of its priority score).

**Comment by xavierfav** [comment]
Awesome, I like the idea!
The flexibility of this new prioritization approach is very enticing.

@edufonseca do you validate?

**Comment by edufonseca** [comment]
sounds good!
