### ISSUE TITLE
Add criteria for dataset release

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#20]
Currently, there is no strategy for the creation of a dataset release.

In the file datasets/tasks.py, generate_release_index() should:
- create a DatasetRelease, and add the Annotations that are considered as correct according to a strategy criteria.
- create file with the FS ids, ontology labels, ... (already implemented, but maybe the structure of the file may be changed).

**Comment by ffont** [comment]
Some notes:

- IIRC, the `DatasetRelease` object is already created when the task is run. The task receives a `release_id` parameter that is used then to query the `DatasetRelease` object. What you need to do is to link the specific `Annotation` objects with a specific `DatasetRelease` (only those annotations which we consider to be good for the release). To do this you probably need to add a `OneToMany` relation from `Annotation` to `DatasetRelease`.

- The file is needed so that the download script can retrieve it later and it does not need to be created every time someone wants to download the content. The current structure of the file as it is implemented is fine, it should simply be integrated with the process described in the previous bullet point and only add the annotations relevant for the ground truth.

**Comment by xavierfav** [comment]
The notion of release has evolved and involves more things.
Therefore, a release creation could be separated into two steps:
- Ground truth generation (this issue)
- Design of subsets #24

**Comment by xavierfav** [comment]
Ground truth generation is now done in real time and added in the `GroundTruthAnnotation` table.
