### ISSUE TITLE
Score for prioritizing categories to raters

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#36]
#29 discusses a way of showing a list of sound categories for raters to select. A proposed criterion to sort them is by using a numeric score, as follows.

`Score = G - #GT `
 
Where:
* _G_ is the the **Goal**, which, for starters, could be the _balanced_ version of **Full subset**, ie, every category must have _G_ sound clips. For instance, G =10.
 
* _#GT_ is the number of annotations that become GT by user agreement, that is, 2 users rating the annotation as _Present_.
 
The initial state of a category is: _Score = G_. At the end, _Score = 0_ (ie, mission accomplished for the mentioned Goal). When _Score_ is not positive, the category could be blocked (preventing users from choosing the category).

Note:
The _Score_ above should account for the number of votes present in a category; the greater the number of votes, the closer to GT generation.

**Comment by xavierfav** [comment]
#GT has been added to `TaxonomyNode` model under the _nb_ground_truth_ field.
It make more sense to store this information instead of the priority score, since _nb_ground_truth_ is more informative and the calculation of the score can be easily done from _nb_ground_truth_.

The _Goal_ may not be so useful. We want to be able to sort the `TaxonomyNode` by  _nb_ground_truth_, but nothing has been decided yet when the goal is reached for a `TaxonomyNode`. The Goal should maybe be related to `Dataset`.

**Comment by xavierfav** [comment]
A score for prioritizing categories is functional.
_nb_ground_truth_ has been added to `TaxonomyNode`.
A periodic task calculates the number of ground truth and update the corresponding field.

Nothing has been done related to the _Goal_. 
For now there is no plan about how to use it.
