### ISSUE TITLE
Add login required dataset_taxonomy_table_choose

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#45]
Decorator `@login_required` is needed in at least the view function _dataset_taxonomy_table_choose_

**Comment by alastair** [comment]
Be careful about where you put `@login_required` - it makes more sense to put it at http://localhost:8000/fsd/contribute/choose_category/ instead of in the table view, because you want the entire browser to redirect to the login page, not just the contents of the table.

You could have a custom checker which checks if the user is logged in and if not, returns HTTP401.
The idea here is that if the use loads the main category page then they get redirected to the login page. If someone manually tries to load the URL which shows this table then they should just get an "unauthorised" error, since this isn't really a public URL.

**Comment by xavierfav** [comment]
Adding `@login_required` to _choose_category()_ ('dataset_taxonomy_choose_category.html') already take care of redirecting the user to the login page.

Then for the "unauthorized" error, how can I know if the user tried to manually load the URL?

**Comment by xavierfav** [comment]
The following changes have been merge to master:

- Add login required to choose_category()
- Add check if user is authenticated or raise 401 dataset_taxonomy_table_choose()
