### ISSUE TITLE
Change dataset stats displayed

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#56]
In the platform, we show some statistics about the dataset.
Now that we can vote several time the same sound, and that we have a strategy for ground truth generation. The actual statistics are not reflecting the state of our dataset.

The "% validated annotations" correspond to how much annotation have been voted once.
Also, "validated" sounds like the annotation is rated as "Present" (or no?).

In the taxonomy category table, "% validated annotations" (which was corresponding to the % of annotations that have been voted once) has been change to  "# validated annotations", and it is now showing the number of annotations that are considered as "Present" ground truth.

Maybe we should use a different term than "validated". In the paper, this term is also used and refers to the % of annotations that have been voted once (vote being present or not).

**Comment by edufonseca** [comment]
After discussing with @xavierfav , we propose the following.

**In the _release_ table (at the top of https://datasets.freesound.org/fsd/)**, we could show the following stats (1 and 2 for sure, 3 maybe):

1. _**% validated annotations**_. We can understand it as the % of annotations that have begun the process of subjective validation, i.e.:
  * % of annotations that have been voted at least once, or
  * % of annotations for which there is a number of users _x_ that have validated it (through the validation task) where _x_ can be [1,2,3,...]. Note that, for the computation of this stat, the value of _x_ does not really matter. Either the annotation has been validated or not.

Also note that **the result of a validation can be: PP, PNP, U, or NP**.

2. We **should** add something like: _**% ground truth (annotations?)**_. This is defined as % annotations that meet the following conditions:
  * have been validated by more than one user, and
  * there is _rater agreement_ in one of the "Present" responses, that is, one of the following:
    1. two users  have rated the annotation as PP
    2. two users  have rated the annotation as PNP

Note that the 3rd case where one user rates it as PP and another as PNP is not enough, since in the future, it will be desirable to be able to differentiate between subset of PPs and subset of PNPs.

3. We **could** add something like: _**# votes**_. This is defined as the number of subjective ratings that the annotations have received. 

For example, suppose that an audio sample has one annotation automatically generated by the tag-based mapping. We seek annotation agreement, which, in the _worst_ case, would imply gathering 5 votes (4 initial different votes + the 5th that agrees with one of them). This would mean:
* 5  votes for _**# votes**_
* just 1 validated annotation, for the sake of **% validated annotations**
* if there is agreement on PP or PNP, 1 ground truth annotation, for the sake of **% ground truth annotations**

For clarity, we propose that the suggested terms are explained in the platform, with a legend implemented in a similar way to that of a **HELP** button that shows the _Summary of Instructions_ in the _validation task_. 

If the  _**# votes**_ is included, we propose to remove **Avg annotations per sound** from the release table and put it in the aforementioned legend, along with the terms explanation.

---

**In the  _taxonomy category_ table (at the bottom of https://datasets.freesound.org/fsd/)**, the stat currently named as "# validated annotations" should:
* show current value, ie, the number of annotations (since we are in a single category, annotation equals audio clip) that have agreement on PP or PNP, hence they are considered as ground truth.
* but its name should be changed to **# ground truth**

---

**In the  _validation page_ of a sound category** (ie, within the validation task), we currently show:
*  % validated | 6.12% (81 out of 1323 annotations)

Instead of showing the validated ones, it is more informative to show the ground truth:
*  % **ground truth** | 4.78% (63 out of 1323 annotations)

**Comment by xavierfav** [comment]
1. % validated annotations:
Calculation does not change

2. % ground truth:
This notion is confusing. Is it % of annotation that have been validated or of total annotations. 
We do not know if an annotation is ground truth or not before having validated it enough.
I suggest to show #ground truth.
This is available in the context variable provided in by `dataset_taxonomy_table` rendering _dataset_taxonomy_table.html_ template:
```
% for node in dataset_taxonomy_stats.nodes_data %}
...
    <td>{{ node.nb_ground_truth }}</td>
```

3. #votes
I don't find it very informative.
However, here is how to calculate it for a TaxonomyNode with node_id <node_id>:
`Vote.objects.filter(annotation__taxonomy_node__node_id=<node_id>).count()`



I have one concern about ground truth calculation.
We should populate annotations (or ground truth annotations) in parents (when it makes sense) for calculating these numbers.
For instance, having ground truth annotations for _Drum_ should add ground truth annotations to his parent _Percussion_.

Also, because of how we prioritize annotations and categories, this population of ground truth annotation should be taken seriously.
There is also the problem of having candidates for parent and children annotations. 
We should take care of proposing to validate leaf nodes annotations first before proposing them for parents (to avoid multiple voting in the same path of the ontology when not needed).

**Comment by xavierfav** [comment]
After a quick meeting, we decided to re-think the stats displayed about the dataset.

**Comment by xavierfav** [comment]
You can see the changes on the branch iss56.
I've almost followed what what said in the [doc](https://docs.google.com/document/d/163-1nlAaMyzCmrcfP348MvOzPd6uSNuf-jwtVLBKzVM/edit?ts=59ce0683).
Except for the things related to `DatasetRelease`, that for now are not needed.

Need the explanation text about the FSD dataset.
