### ISSUE TITLE
Prioritize annotations corresponding to short clips

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#69]
For now, when a user contributes to the _validate category annotations_ task, the annotations presented to him are the ones that are not considered as ground truth, that he never voted and following this order:
 (I am not including verification annotations in purpose to not mess the explanation here)
1. the ones that have been already voted at least once

If the number of annotations that follow the last criteria is less than 12 (number of annotations to vote in one form), 

2. annotations that have never been voted are added.

---
It was decided to prioritize the annotations which correspond to clips that have a short duration.
For that purpose, I propose to do the following:

1. Add the annotations that have been voted at least once
2. If we don't reach 12, add the annotations that have never been voted and that correspond to clips of a duration < 10 sec
3. If we don't reach 12, add the remaining annotations

At first, we will concentrate at validating the annotations that have already been voted at least once, so we want quickly to get an agreement. Once there are no annotations with at least one vote, we concentrate on the short ones.

---

For that, it is needed to add a step in the `contribute_validate_annotations_category` view function: after selecting the annotations that have been already voted and if the amount obtained does not reach 12.

**Comment by edufonseca** [comment]
We can think of what happens when, in a category, sounds <10s are already validated.
Currently files are in the range [0:90] seconds, with 40% of the samples <6s.
Sounds' variable length implies the need for certain classification approaches. 

When it comes to sounds' duration, for FSD 1.0 we could understand “short” files as the most interesting (and abundant) and try to avoid large differences in duration. As suggested in ISMIR 2017, we could prioritize the annotation of short sounds according to the following ranges:
1) 0-10s (already implemented)
2) when 1) is over: 10-20s
3) when 2) is over: 20-30s

Goal: a more homogeneous release in terms of sound duration (probably easier to handle and more reasonable)

**Comment by xavierfav** [comment]
This issue will be addressed in #133.
