### ISSUE TITLE
Designing Explicit part of Training phase

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#71]
After choosing a sound category, the user is redirected to a new page which is the **explicit** part of the **training phase**.

Aim: show context of the selected category **AND** those of the siblings/parents in order to help the rater create his judgement before proceeding with the task. 

In this page we list:
* Selected category
* Parent(s) of Selected category
* Siblings of Selected category

For every category we display:
* place in the hierarchy
* description
* direct children
* good sound examples (#30)
* anything else?

WE should specify this more:
* web design
* how many examples
* ?

**Comment by xavierfav** [comment]
I don't understand very well, "for every category we display" ? 
The user has already selected a category to contribute to, you mean for all the parents and sibling we display these informations? 
It seems like being too much information if we display all that. Is it possible to put 15 descriptions of categories in the same page? For me it is a bit excessive. The user could get lost in so much information.

I liked the idea Jordi proposed last time. 
Having a page containing a lot of informations (similar to the one proposed here) to show in the explicit part. And having another light one that we show together with the vote pages (similar to the one implemented now in the platform).
So let's maybe propose two version of the explicit training page (one extended and one light).

About the "place in the hierarchy", what would be the way to display that? Show the path (Human Sounds > Human voice > ...), or show a tree visualization?

For the number of good sound examples, we were thinking of 2 for normal categories (the one which have only one parent), and showing one for each possible semantic meaning for the one having multiple parents (e.g. Hiss: one cat, one snake, one steam). Do you think we will have enough annotated examples for that? Otherwise we could maybe also give an example from Youtube with the examples provided in the ontology.json file.
However, the categories having multiple parents might not be a big problem. According to [the analysis we did](https://docs.google.com/spreadsheets/d/19i9FS3VM_w0IxpX6oCp8qC9eR3zov4jt3ryvLvdqkGI/edit#gid=435729435), only a few category have parents that have really different meaning. Most of them just show that there is a relation between sound events and concepts that always make sense.
