### ISSUE TITLE
Add link in category hierarchy path

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#9]
It would be nice to be able to navigate through categories from the hierarchy path (for both exploring and annotating), like in Audio Set website.

**Comment by ffont** [comment]
Sounds reasonable. Some hints to to that:

- The hierarchy path is calculated in the method [`get_hierarchy_paths `](https://github.com/MTG/freesound-datasets/blob/master/datasets/models.py#L41) from `Taxonomy` model. It takes as an argument a `node_id` (node=category).
- This function returns the hierarchy path as a string which renders node names, eg: "Animal > Wild animals > Snake"
- In order to be able to add links, we want to have the node names and the node url ids (which are needed to build the url in the template). This function could return a list of nodes sorted according to the path, instead of the names of the nodes already rendered in a string. Then in the template we can iterate over the nodes and add the links, like we do for the [direct children nodes](https://github.com/MTG/freesound-datasets/blob/master/templates/contribute_validate_annotations_category.html#L57).
