### ISSUE TITLE
Signalling presence of another label in a audio clip

### ISSUE THREAD

**Issue by fabio12345** [MTG/freesound-datasets#90]
From using the current validation user interface you can only say whether the audio clip contains an audio class - but it is not possible to report what other labels it contains. 

For example, imagine you are given fireworks clips to validate. There might be a number of other labels in it, such as crowds, male speech, female speech, child speech and so on. It would be good to be able to report that those labels also apply to the clip, so that the labelling is more complete. 

Have you considered adding this feature?

**Comment by xavierfav** [comment]
We though about adding a single-ressource annotation task in which users annotate a single audio using concepts of the ontology. In this way, we could achieve a more complete labelling (#35).

The main challenge is that the ontology is huge, and letting a user annotating with any of label from it is a very hard task. From what you say, maybe you suggest that we could also propose a task where a few classes are considered at the same time (making groups of labels that often co-occur such as fireworks with crowds, etc...) when validating? A vote from could include a list of the different labels considered in a way that a user could easily validate.


Getting complete labelling is one of our main concern for the datasets produced in our platform. We also though about ways to prioritize annotations in the validation task present in the platform, so that we force the validation of all the candidate annotations of a sound (e.g. simply prioritizing annotations referring to sounds that have already other validated annotations) and therefore improving the labelling completeness.
However, we miss adding some other important features to make this prioritization having the expected effect (force the validation of different labels from different _paths_ in the hierarchy and not force the validation of parent classes): the hierarchy of the AudioSet Ontology is not used yet for selecting the appropriate candidate annotations to be voted. Thus, validations of `Bark` is not validating `Dog` and all its parent in the hierarchy. For ambiguous cases (multiple parents), a disambiguation is needed.
